// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "AudioVision",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "AudioVision",
            targets: ["AppModule"],
            bundleIdentifier: "audiovisionapp",
            teamIdentifier: "PXJDJW8Z9X",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .speechRecognition(purposeString: "This app needs access to speech recognition to turn your speech into commands."),
                .microphone(purposeString: "This app needs access to your microphone to detect your speech."),
                .photoLibrary(purposeString: "This app requires access to photo library to detect text in images selected from the library."),
                .camera(purposeString: "This app requires access to camera so you can capture images to detect text in them.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)
